### ISSUE TITLE
Potential reasons for stuck building wheel for droput-layer-norm

### ISSUE THREAD

**Issue by radarFudan** [HazyResearch/safari#17]
Hi! It's a really nice repo and the code is quite clear to read.

As I was trying to run the hyena code for language model, it seems the building for third layer_norm package is stuck and I've waited for the third install a whole day. 

```
cd ./csrc/fused_dense_lib && pip install .
cd ../xentropy && pip install .
cd ../layer_norm && pip install .
```

I just wonder if it's normal for a build to take so long or some bug with my configuration. 

Basically the current output for (stuck terminal) is:
```
Building wheels for collected packages: dropout-layer-norm
  Building wheel for dropout-layer-norm (setup.p) ... |
```

Thank you so much for reading my issue!

**Comment by radarFudan** [comment]
Just found this issue has been proposed in flash-attention repo(https://github.com/HazyResearch/flash-attention/issues/180)

**Comment by rishabh-akridata** [comment]
@radarFudan Did you manage to solve this issue? I am also facing the same issue.
